spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental
    username: postgres
    password: Shotlandiya2022
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    format:
      date: iso






